# Generated by Django 3.2.12 on 2023-09-09 06:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name_text', models.CharField(default='', max_length=200)),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now)),
                ('task_name_ptich', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
