# Generated by Django 3.2.12 on 2023-09-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
