# Generated by Django 3.2.12 on 2023-09-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_newsmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='title_en',
            field=models.CharField(default=' ', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='title_ru',
            field=models.CharField(default=' ', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='title_uz',
            field=models.CharField(default=' ', max_length=50, null=True),
        ),
    ]
