# Generated by Django 3.2.12 on 2023-09-23 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20230923_1010'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='newsmodel',
            table='News',
        ),
    ]
